export interface PDFReportData {
  websiteUrl: string
  reportType: 'snapshot' | 'detailed'
  sections: Record<string, string>
}

const SECTION_LABELS: Record<string, { category: string; title: string }> = {
  introduction: { category: 'OVERVIEW', title: 'Executive Summary' },
  whySeoMatters: { category: 'CONTEXT', title: 'Why This Matters' },
  currentVisibility: { category: 'CURRENT STATE', title: 'Your Organic Visibility' },
  contentAuthority: { category: 'AUTHORITY', title: 'Content & Topic Strength' },
  technicalStructure: { category: 'INFRASTRUCTURE', title: 'Technical Foundation' },
  opportunities: { category: 'OPPORTUNITIES', title: 'Highest-Leverage Growth Areas' },
  nextSteps: { category: 'ACTION PLAN', title: 'Recommended Next Steps' },
  currentPositioning: { category: 'POSITIONING', title: 'Current Market Position' },
  technicalReview: { category: 'TECHNICAL', title: 'Technical Review' },
  competitorPresence: { category: 'COMPETITION', title: 'Competitive Landscape' },
  keywordDirection: { category: 'KEYWORDS', title: 'Keyword Direction' },
  contentStrategy: { category: 'CONTENT', title: 'Content Strategy' },
  roadmap: { category: 'ROADMAP', title: '90-Day Action Plan' },
  conclusion: { category: 'CONCLUSION', title: 'Final Recommendations' },
}

export function buildPDFHTML(data: PDFReportData): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const sectionsHTML = Object.entries(data.sections)
    .filter(([_, value]) => value && value.length > 10)
    .map(([key, value]) => {
      const label = SECTION_LABELS[key] || {
        category: key.toUpperCase(),
        title: key,
      }
      return `
        <div class="section">
          <div class="section-category">${label.category}</div>
          <h3 class="section-title">${label.title}</h3>
          <p class="section-body">${value}</p>
        </div>
      `
    })
    .join('')

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SEO Report — ${data.websiteUrl}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #fff;
    color: #0a0a14;
    padding: 48px;
    max-width: 800px;
    margin: 0 auto;
    font-size: 14px;
    line-height: 1.6;
  }
  .header {
    padding-bottom: 24px;
    margin-bottom: 32px;
    border-bottom: 3px solid #10b981;
  }
  .header-top {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
  }
  .logo {
    font-size: 22px;
    font-weight: 800;
    color: #0a0a14;
    letter-spacing: -0.02em;
  }
  .logo span { color: #10b981; }
  .report-badge {
    background: #ecfdf5;
    border: 1px solid #10b981;
    color: #065f46;
    padding: 5px 14px;
    border-radius: 100px;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }
  .website-url {
    font-size: 24px;
    font-weight: 800;
    color: #0a0a14;
    letter-spacing: -0.02em;
    margin-bottom: 6px;
  }
  .report-meta {
    font-size: 13px;
    color: #6b7280;
  }
  .section {
    margin-bottom: 24px;
    padding: 20px 20px 20px 24px;
    border: 1px solid #e5e7eb;
    border-left: 3px solid #10b981;
    border-radius: 8px;
    page-break-inside: avoid;
  }
  .section-category {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.1em;
    color: #9ca3af;
    text-transform: uppercase;
    margin-bottom: 4px;
  }
  .section-title {
    font-size: 15px;
    font-weight: 700;
    color: #0a0a14;
    margin-bottom: 10px;
  }
  .section-body {
    font-size: 13px;
    color: #374151;
    line-height: 1.75;
  }
  .footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e5e7eb;
    text-align: center;
    font-size: 12px;
    color: #9ca3af;
  }
  @media print {
    body { padding: 24px; }
    .section { page-break-inside: avoid; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="header-top">
      <div class="logo">SEO<span>&bull;</span>AI</div>
      <div class="report-badge">${data.reportType.toUpperCase()} REPORT</div>
    </div>
    <div class="website-url">${data.websiteUrl}</div>
    <div class="report-meta">Generated on ${date} &middot; AI SEO Advisory Report</div>
  </div>
  ${sectionsHTML}
  <div class="footer">Generated by SEO AI &middot; ${data.websiteUrl} &middot; ${date}</div>
</body>
</html>`
}
